[package]
name = "computor_v2"
version = "0.1.0"
authors = ["Anatoliy Lischynsky <iamnotacake@protonmail.com>"]
edition = "2018"

[build-dependencies]
lalrpop = "*"

[dependencies]
lalrpop-util = "*"
# regex = "*"
